on:
  workflow_dispatch:
    inputs:
      C4C:
        description: 'Deploy C4C'
        required: false
        default: 'false'
      SFDC:
        description: 'Deploy SFDC'
        required: false
        default: 'false'
      API:
        description: 'Deploy API'
        required: false
        default: 'false'
      FINANCE:
        description: 'Deploy Finance'
        required: false
        default: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Construct Terraform Targets
      run: |
        # Extract inputs from the workflow
        C4C="${{ github.event.inputs.C4C }}"
        SFDC="${{ github.event.inputs.SFDC }}"
        API="${{ github.event.inputs.API }}"
        FINANCE="${{ github.event.inputs.FINANCE }}"

        # Initialize the TARGETS variable
        TARGETS=""

        # Loop through the options and add valid targets
        for OPTION in C4C SFDC API FINANCE; do
          VALUE=$(eval echo \$$OPTION)  # Dynamically get the variable value
          if [[ "$VALUE" == "true" ]]; then
            TARGETS+="-target=module.bigquery[\\\"${OPTION}\\\"] " 
          fi
        done

        # Output the constructed TARGETS to the GitHub environment
        echo "TF_TARGETS=$TARGETS" >> $GITHUB_ENV

    - name: Use Constructed Terraform Targets
      run: |
        echo "Using the following Terraform targets:"
        echo $TF_TARGETS
